Gravity manipulation field
ZeroFoxStudio/Ruins-of-the-Past pull request #37
Opened 2023-10-26 07:40 UTC by Lucasje2

https://zerofox.atlassian.net/browse/ROTP-107?atlOrigin=eyJpIjoiYTFkNDA4ZDY3MmJmNDIxMGE4MDE0MmJiMmZlOTJlMjciLCJwIjoiaiJ9

2023-10-26 09:11 UTC, Extiriority requested changes
Try  to change the animal values on gravity force variable to about 3 so it floats more consistently
![image](https://github.com/ZeroFoxStudio/Ruins-of-the-Past/assets/68713110/34c90cee-af62-4798-a7e3-34ccf6168e8e)

2023-10-26 09:11 UTC, Extiriority commented on Assets/Scripts/GravityManipulationField/MatchParticleSystemSize.cs
> +        }
Ditto

2023-10-26 09:11 UTC, Extiriority commented on Assets/Scripts/GravityManipulationField/MatchParticleSystemSize.cs
> +        }
Ditto

2023-10-26 09:11 UTC, Extiriority commented on Assets/Scripts/GravityManipulationField/MatchParticleSystemSize.cs
> +            }
Statement has no default

2023-10-27 07:58 UTC, Lucasje2 commented
This branch has been rejected because the malbers package has a gravity/wind field prefab that we can use

2023-10-27 07:58 UTC, closed without merging